export const bodyWidgetDesignRegistry = {
  version: 4,
  defaultPlacement: "E",
  defaultScore: 9.5,
  absoluteFreedomRule: "ALLES KAN. Never enumerate possible content, element types, compositions, placements, or visualizations as a definition of what is allowed. Any enumeration creates an unintended boundary. Describe only the governing purpose and constraints; possibility itself remains unlimited.",
  scaleSystem: {
    baseCardSize: 288,
    outerSpace: 20,
    topZone: 33,
    zoneGap: 15,
    centerZone: 152,
    bottomZone: 33,
    sequence: [20, 33, 15, 152, 15, 33, 20],
    clipZoneContent: false,
    clippingRule: "Zones and subzones constrain layout geometry but must not clip glyphs or visual details that extend beyond their box.",
    visualScalingRule: "A visualization scales proportionally as one object: geometry, stroke, typography, and internal spacing follow the same scale ratio. If the result becomes unusable, switch to another composition instead of scaling individual parts at different rates.",
    resizeContract: [
      "Every resized card keeps the complete E structure: outer spacing, top zone, first gutter, center zone, second gutter, and bottom zone.",
      "The base vertical sequence is 20 / 33 / 15 / 152 / 15 / 33 / 20 at 288 × 288. Its zone proportions remain authoritative at every temporary prototype size.",
      "Top, center, bottom, their subzones, and their contents expand with the complete resized card. A resized card may not leave the original 288 × 288 composition floating inside unused space.",
      "The current prototype preserves the same composition while resizing. Widget-specific rearrangements, additional information, and allowed-size decisions are deliberately deferred.",
      "Every widget variant supports 1x1, 1x2, and 2x1 by default.",
      "Supported sizes are continuous: reaching a larger footprint requires every intermediate footprint on that axis to be supported.",
      "Taking the resize handle reveals every valid destination footprint before the pointer moves; dragging highlights and snaps only to those visible destinations.",
      "The resize map always includes the current footprint. A valid size never disappears merely because the widget already occupies it.",
      "Geometry and content scale without horizontal or vertical distortion. Flexible visual containers use all newly allocated space while typography, icons, strokes, gaps, and outer spacing follow one coherent scale.",
      "Zones and subzones never introduce automatic internal padding. Deliberate whitespace belongs to the individual composition, not to the zone system.",
      "A footprint uses the dimension it actually gains. Added height does not justify crowding unchanged width, and added width does not justify wasting new horizontal space.",
    ],
  },
  visualLanguage: {
    status: "locked baseline",
    implementationRule: "Widgets are real, responsive, data-driven UI components. Fake screenshot-like visuals and decorative charts without functioning data logic are not allowed. Fictitious data is allowed while prototyping.",
    card: {
      surface: "light",
      background: "#FFFFFF",
      foreground: "#18202A",
      border: "#E4E7EB",
      cornerRadius: 22,
      shadow: "0 8px 22px rgba(24,32,42,.055)",
      rule: "The card remains a light neutral surface; the widget accent color never becomes the card background.",
    },
    typography: {
      family: "Inter",
      title: { size: 15, weight: 600, tracking: "-0.015em" },
      metadata: { size: 11, color: "#747D89", lineHeight: 1.2 },
      standardDetailSize: 11,
      rule: "Hierarchy, size, weight, and color are decided case by case from meaning and readability. Comparable semantic roles should remain visually harmonized unless a deliberate difference communicates meaning.",
    },
    icons: {
      pack: "Tabler Icons",
      standardSize: 24,
      color: "widget accent",
      topPlacement: "right",
      rule: "Placement E always includes its fixed icon in the top-right. Icons elsewhere may appear only as deliberate content inside an available element slot.",
    },
    color: {
      accentRule: "Each widget has one user-selectable accent hue. Variations normally remain lighter or darker shades of that same hue.",
      semanticException: "Additional colors are allowed only when they communicate a necessary universal semantic state such as warning, danger, success, or comparison.",
      neutralPrimary: "#18202A",
      neutralSecondary: "#747D89",
      rule: "Accent color carries meaning and emphasis; it is not spread decoratively across unrelated content.",
    },
    visualization: {
      generalRules: [
        "The center visualization is the main visual idea of the widget, not filler around a number.",
        "Every visual encoding must correspond to understandable data or state.",
        "Related geometry, typography, strokes, and spacing scale together according to the scale system.",
        "Rounded geometry is the default visual character. Sharp geometry is used only when deliberately selected for structural precision.",
        "The visualization uses all intentionally allocated space; accidental padding, clipping, or unused internal margins are not allowed.",
      ],
      lineCharts: {
        engine: "Recharts",
        dataRule: "Line, grid, scale values, and live metrics derive from functioning datasets and the same chart scale.",
        xAxis: "Numeric first-to-last data domain with no automatic categorical start or end padding.",
        yAxis: "The displayed domain follows the active dataset so its visible minimum and maximum use the available plot height. A future production metric may choose a fixed semantic domain when comparison requires it.",
        curve: "Monotone, smoothly rounded data line without permanent point markers.",
        mainStroke: { width: 3, color: "widget accent", lineCap: "round", lineJoin: "round" },
        smallMultipleStroke: { width: 2, color: "widget accent", lineCap: "round", lineJoin: "round" },
        grid: { width: 0.8, color: "#D9DEE5", opacity: 1, lineCap: "butt", verticalLines: false },
        scaleRail: { width: 22, gapFromPlot: 0, alignment: "right", labelColor: "#87909C", labelSize: 9, labelBackground: "none" },
        scaleRules: [
          "Grid lines and scale values are generated from the same Y-axis ticks and must remain perfectly aligned.",
          "The plot ends directly against the scale rail; no unused gap exists between them.",
          "Scale labels sit at the outer edge of their zone and never cover the data line.",
          "Standard charts use maximum, midpoint, and minimum references; tiny small multiples use only maximum and minimum.",
          "Titles, chart plots, and values occupy separate layout containers so charts cannot overlap text.",
          "Small multiples that are meant to be compared use the same metric logic and consistent construction.",
        ],
      },
      rings: {
        radius: 45,
        strokeWidth: 8,
        lineCap: "round",
        track: "soft shade of the widget accent",
        value: "widget accent",
        rule: "A ring fills its allocated slot while preserving the same proportional geometry, stroke, text, and internal spacing when scaled.",
      },
      bars: {
        cornerRadius: "rounded-md",
        rule: "Bars, reservoirs, and filled rectangular measures use the shared rounded geometry unless their data meaning deliberately requires another shape.",
        labelRule: "Labels, plots, and values receive distinct logical layout space; content inside a bar or block is aligned within that block rather than inherited from the zone's outer anchoring.",
      },
    },
    interaction: {
      currentPrototype: "A shared slider changes the fictitious line-chart datasets and their derived visible values in real time.",
      futureRule: "Exact detail may appear through hover, focus, or tap without permanently cluttering the default visualization; interaction must remain mobile-compatible.",
      hoverLanguage: {
        audit: "Every new widget variant is reviewed element by element at every supported size before it is considered complete. For each element, deliberately decide whether hover, keyboard focus, and tap reveal useful hidden meaning or whether the element should remain still.",
        freedom: "Hover behavior is decided case by case. Anything can react and anything can remain still; this freedom is never replaced by a closed list of permitted interactive elements.",
        card: "The complete widget receives only a subtle border and shadow response; it never lifts, scales, or rearranges.",
        data: "A visualization with hidden time or reading dimensions reveals the nearest real datapoint. Lines use a temporary point and guide; bar distributions emphasize only the selected bar.",
        meaning: "Only ambiguous values, statuses, and standalone state icons receive a hint. The hint uses the fewest possible words and sits directly beside its trigger, normally 6-8 px away.",
        still: "Clear labelled values, titles, icons, and decorative shapes remain still and receive no redundant tooltip.",
        motion: "Feedback lasts 150 ms with ease-out-quart behavior and is removed when reduced motion is requested.",
        completion: "A hover treatment is incomplete until the same information is reachable through keyboard focus and a touch-compatible interaction.",
      },
    },
  },
  placementRules: {
    E: {
      note: "These rules apply only while placement E is used.",
      top: {
        hasElementSlot: false,
        fixedElements: {
          left: ["title", "short metadata"],
          right: ["icon"],
        },
      },
      center: {
        role: "primary visualization and optional integrated metrics",
        freedomPrinciple: "Anything may exist in the center's element slots, but all slots must collectively serve one coherent primary visualization.",
        rules: [
          "The center is composed of element slots, and anything is allowed inside every slot.",
          "Freedom inside the slots always serves the center's core purpose: forming the widget's primary visualization.",
          "Do not subdivide the center merely to store movable supporting information while useful bottom-zone space remains empty.",
          "Center and bottom may deliberately collaborate in any distribution, but related rows, columns, edges, and baselines must be intentionally aligned.",
          "Labels and values inside the visualization must remain readable throughout the intended scaling range; do not begin from barely readable base sizes.",
          "Repeated semantic roles should feel harmonized in size and treatment unless a deliberate meaning requires a difference.",
          "No rule restricts the possible visualization, slot content, composition, or relationship between zones.",
        ],
      },
      bottom: {
        type: "free composition zone",
        freedomPrinciple: "Everything is allowed. The rules below guide deliberate thinking but never define or limit the available design possibilities.",
        rules: [
          "The bottom zone is a full composition zone and must never automatically be treated as a footer.",
          "Position does not determine importance. Bottom content may have any degree of prominence, including being the dominant content, or the zone may remain empty.",
          "There is no default alignment. Alignment is chosen deliberately for the individual widget.",
          "There is no automatic small typography. Size and hierarchy follow meaning and readability, not zone position.",
          "There is no automatic gray treatment. Without a deliberate reason to use another treatment, text uses the normal primary treatment.",
          "There is no mandatory inner margin. Content may fill the entire zone or deliberately occupy less space.",
          "In placement E, bottom content is vertically anchored to the lower edge and builds upward, mirroring how top content anchors to the upper edge and builds downward. Horizontal alignment and deliberate exceptions remain free.",
          "Every bottom composition is judged together with that widget's top and center rather than through a universal bottom pattern.",
          "Element slots have no fixed role or content category. Anything is allowed.",
          "A set of variants should explore genuinely different possibilities, including content that uses the full bottom-zone height.",
          "Subzones and their contents remain contained by the main zone and scale with it. Space between subzones is a deliberate composition choice.",
          "Information is not duplicated without a deliberate purpose.",
          "The zone may contain any number of element slots.",
          "The number, width, alignment, and distribution of its subzones are chosen per widget.",
          "Subzones may use any composition whatsoever.",
          "No permanent left slot, right slot, column count, or element type is prescribed.",
          "The outer bottom-zone boundary remains fixed by the E scale system while its internal composition stays free.",
        ],
      },
    },
  },
  vocabulary: {
    elementSlot: "Anything may be placed here. Never define, enumerate, imply, or constrain possible element types; any list would incorrectly limit the design space.",
    fixedElement: "A structural element prescribed by the selected placement language; it is not an element slot.",
    freeCompositionZone: "A bounded zone whose internal layout is decided per widget. It may contain zero, one, or multiple freely sized and positioned element slots.",
    subzone: "An optional subdivision inside a free composition zone. A subzone describes available space, not a mandatory element or semantic role.",
  },
  savedCollections: {
    approvedBodySetV1: {
      status: "preserved",
      description: "The complete approved E-language exploration set: the official E prototype plus the ten Body example widgets. It remains available as a collection even while the hub temporarily focuses on one teaching widget.",
      widgetIds: [
        "body-widget-official-e",
        "body-widget-composition-b",
        "body-widget-composition-c",
        "body-widget-composition-d",
        "body-widget-composition-e",
        "body-widget-composition-f",
        "body-widget-composition-g",
        "body-widget-composition-h",
        "body-widget-composition-i",
        "body-widget-composition-j",
        "body-widget-composition-k",
      ],
      companionPrototype: "Live chart data control is preserved with the collection but hidden during the single-widget lesson.",
    },
    activeTeachingWidget: {
      widgetId: "body-widget-steps",
      label: "Steps",
      reason: "It combines a primary visualization with an integrated metric slot, making it useful for explaining future behavior without privileging a special-case layout.",
    },
  },
  creativeFreedom: {
    rule: "ALLES KAN. Design space is intentionally unbounded; guidance protects purpose and quality without defining a catalogue of allowed outcomes.",
    visualizationRule: "Begin with what the person needs to understand, then invent or select the visual form that communicates it best. Familiar and bespoke visualizations have equal standing.",
    originalityRule: "Do not default to a recurring visual family merely because it already exists elsewhere. Reuse is valid when it is the strongest answer; originality is valid when it creates clearer or more memorable understanding.",
    caseByCaseRule: "Every umbrella, variant, footprint, zone, element slot, and interaction is judged in the context of that exact widget. Shared language creates coherence but never replaces deliberate design judgment.",
    preservationRule: "Approved work is archived as its actual component definition before the active product surface is cleared or replaced, preserving every variant, supported size, behavior, and responsive composition.",
  },
  responsiveVariantModel: {
    vocabulary: {
      umbrella: "The metric or subject family shown once in Available widgets. Removing its final active variant returns the umbrella to that list.",
      variant: "A distinct widget presentation inside one umbrella. Variants preserve the subject's essential information while freely changing visualization, composition, placement, and supporting information.",
      size: "A deliberately supported grid footprint for one specific variant. Sizes are proposed, not assumed to be an unlimited matrix.",
    },
    rules: [
      "ALLES KAN. No fixed zone template, visualization family, placement list, or information list limits a new variant.",
      "Design begins by identifying the complete information universe for the umbrella, including useful derived information, before choosing what each variant and size displays.",
      "Every production umbrella offers at least two variants so a user always has a genuine presentation preference. More variants exist only when they add a meaningfully different and useful way to understand or use the umbrella.",
      "A visual-first variant is the default drawer presentation. A restrained metric-led variant may remain available for people who prefer direct values, but it is not used as a substitute for the umbrella's primary visualization.",
      "Every variant supports 1×1, 1×2, and 2×1 and uses 1×1 as the canonical drawer preview.",
      "Supported footprints are continuous on each axis. A variant cannot offer a farther size while omitting an intermediate size required to reach it.",
      "The resize destination map always displays every supported footprint, including the current one.",
      "The 1×1 version contains the umbrella's essential information. Every larger supported size retains that essential information.",
      "A larger size may add useful secondary information, improve the visualization, or simply provide a deliberate scale-up when extra information adds no value.",
      "Information progression need not form one linear ladder across differently shaped sizes. A wide, tall, and large-square composition may expose different useful secondary information.",
      "Allowed sizes are decided independently for every variant. Unsupported shapes are blocked rather than filled with a weak composition.",
      "Each size is designed case by case. Zones, subzones, element slots, alignment, hierarchy, and composition may change when the footprint changes.",
      "Variants under one umbrella should remain recognizably related through shared essential meaning, not through forced identical layout.",
      "The umbrella icon in Available widgets is the same icon used by its rendered variants.",
      "Every variant and every supported size receives its own element-by-element interaction audit before completion.",
      "Widget positions are persistent product state. Deliberately empty grid cells remain empty; unrelated widgets move only when a real collision requires displacement.",
    ],
    workflow: [
      "Define the umbrella's user purpose and complete information universe.",
      "Decide which genuinely distinct presentations deserve to exist; do not manufacture variants to reach a count.",
      "Define the essential 1×1 information and visualization for each selected variant.",
      "Choose supported footprints and ensure every required intermediate footprint exists.",
      "Design each footprint case by case, using gained dimensions intentionally and retaining essential information.",
      "Audit hierarchy, alignment, clipping, data logic, accent use, hover, focus, tap, resizing, drawer preview, and persistent placement.",
    ],
  },
  stepsUmbrellaPrototype: {
    umbrellaId: "activity.steps",
    essentialInformation: ["recorded step total", "selected period", "data state"],
    optionalInformationUniverse: ["daily goal", "goal completion", "steps remaining", "hourly distribution", "peak hour", "best-hour value", "source and coverage"],
    variants: {
      hourlyBars: {
        visualization: "hourly step distribution",
        allowedSizes: ["1x1", "2x1", "1x2", "2x2"],
        progression: "Every size retains the recorded total and data state. Larger formats may add finer real interval resolution, comparable history, and source or coverage context.",
      },
      goalRing: {
        visualization: "progress toward daily goal",
        allowedSizes: ["1x1", "2x1", "2x2"],
        progression: "Every size retains the recorded total, personal goal, and data state. Larger formats may add remaining steps, real hourly distribution, and comparable goal history.",
      },
      stepField: {
        visualization: "100-cell completion field",
        allowedSizes: ["1x1", "1x2", "3x1"],
        progression: "Every size retains the truthful step field, recorded total, and data state. Larger formats may add goal context, real peak interval, and source or coverage context.",
      },
    },
  },
  productUmbrellasV1: {
    status: "complete design-language examination set",
    productRule: "The set is curated for useful choice rather than maximum variant count. Every retained alternative changes how the user understands the subject.",
    umbrellas: {
      recovery: { variants: ["recovery factors", "readiness ring"], reason: "causal inputs versus immediate readiness" },
      sleep: { variants: ["stage timeline", "sleep score"], reason: "night structure versus glanceable quality" },
      steps: { variants: ["hourly bars", "goal ring", "step field"], reason: "distribution, goal progress, and completion texture are three genuinely distinct preferences" },
      heartRate: { variants: ["live trend", "daily range"], reason: "moment-to-moment movement versus current position inside the day" },
      hrv: { variants: ["seven-day bars", "baseline balance"], reason: "recent pattern versus personal-baseline interpretation" },
      stress: { variants: ["daily trend", "load bands"], reason: "chronology versus distribution of intensity" },
      bloodOxygen: { variants: ["night samples", "overnight range"], reason: "sample texture versus compressed safety range" },
      respiratoryRate: { variants: ["nightly trend", "seven-night rhythm"], reason: "continuous change versus comparable nightly readings" },
      temperature: { variants: ["baseline trend", "deviation bars"], reason: "direction through time versus signed distance from baseline" },
      dailyStrain: { variants: ["activity load", "target ring"], reason: "source contribution versus progress toward productive load" },
    },
  },
  highestPotential: "G",
  activeAlternatives: ["A", "H", "G", "B"],
  excludedFromRanking: ["F"],
  ranking: ["E", "A", "H", "G", "B", "J", "I", "C", "D"],
  placements: [
    { placement: "a", letter: "A" },
    { placement: "c", letter: "B" },
    { placement: "d", letter: "C" },
    { placement: "e", letter: "D" },
    { placement: "f", letter: "E" },
    { placement: "l", letter: "F" },
    { placement: "h", letter: "G" },
    { placement: "i", letter: "H" },
    { placement: "j", letter: "I" },
    { placement: "k", letter: "J" },
  ],
} as const;

export type BodyWidgetPlacement =
  (typeof bodyWidgetDesignRegistry.placements)[number]["placement"];
